<Project>
  <PropertyGroup>
    <WarnOn>FS0193,FS1182,FS3218</WarnOn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' != 'Debug' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MSBuildTreatWarningsAsErrors>true</MSBuildTreatWarningsAsErrors>
  </PropertyGroup>
</Project>
