name: gwallet
base: core22 # the base snap is the execution environment for this snap
version: '0.6.408.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: minimalistic cryptocurrency brainwallet # 79 char long summary
description: |
  Non-custodial, minimalistic and pragmatist opensource crossplatform
  lightweight brainwallet for people that want to hold the most important
  cryptocurrencies in the same application with ease & peace of mind.
license: MIT
icon: logo.png

# grade must be 'stable' (without the quotes) to release into candidate/stable channels
grade: stable

confinement: strict

layout:
  /usr/share/.mono:
    symlink: $SNAP/etc/mono/certstore

apps:
  gwallet:
    command: bin/gwallet
    plugs: [network]

parts:
  gwallet:
    plugin: dump
    source: ./staging
    stage-packages: [mono-devel]

  certs:
    plugin: dump
    source: /etc/mono
    organize:
      certstore: etc/mono/certstore

