name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

  # to execute once a day (more info see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule )
  schedule:
    - cron: "0 0 * * *"


# FIXME: figure out why we need to clean after make if we
# want 'make strict' target to really happen without
# assuming the binaries from previous build are good
# (msbuild bug?)

jobs:
  macOS--dotnet6-and-mono:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.113'
    - name: Install specific Xamarin.iOS and Xamarin.Android versions
      run: |
        wget https://download.visualstudio.microsoft.com/download/pr/81c41aaa-a3d7-4875-8416-d04b472379b7/21d9f6c5ad3a6bc2479b2ec4b0685b6c/xamarin.ios-16.0.0.72.pkg
        sudo installer -pkg xamarin.ios-16.0.0.72.pkg -target /
        wget https://aka.ms/xamarin-android-commercial-d17-3-macos --output-document=xamarin.android-13.0.0.0.pkg
        sudo installer -pkg xamarin.android-13.0.0.0.pkg -target /
    - name: Check versions
      run: |
        mono --version
        /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch --version
        ls -l /Library/Frameworks/Xamarin.Android.framework/Versions/
    - name: run
      run: make run

  macOS--mono-only:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: HACK to emulate dotnet uninstall
      run: sudo rm -f `which dotnet`
    - name: Install specific Xamarin.iOS and Xamarin.Android versions
      run: |
        wget https://download.visualstudio.microsoft.com/download/pr/81c41aaa-a3d7-4875-8416-d04b472379b7/21d9f6c5ad3a6bc2479b2ec4b0685b6c/xamarin.ios-16.0.0.72.pkg
        sudo installer -pkg xamarin.ios-16.0.0.72.pkg -target /
        wget https://aka.ms/xamarin-android-commercial-d17-3-macos --output-document=xamarin.android-13.0.0.0.pkg
        sudo installer -pkg xamarin.android-13.0.0.0.pkg -target /
    - name: Check versions
      run: |
        mono --version
        /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch --version
        ls -l /Library/Frameworks/Xamarin.Android.framework/Versions/
    - name: run
      run: make run

  macOS--dotnet6-only:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.113'        
    - name: HACK to emulate mono uninstall
      run: sudo rm -f `which mono` && sudo rm -f `which msbuild`
    - name: run
      run: make run

  windows--dotnet6-and-legacyFramework:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.113'
    - name: run
      run: .\make.bat run

  windows--legacyFramework-only:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: HACK to emulate dotnet uninstall
      run: del $(where.exe dotnet)
    - name: run
      run: .\make.bat run

  windows--dotnet6-only:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.113'
    - name: HACK to emulate legacy .NETFramework uninstall
      run: del $(& "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -find MSBuild\\**\\Bin\\MSBuild.exe)
    - name: run
      run: .\make.bat run

  linux22-github--dotnet-and-mono:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: install missing dependencies
      run: sudo apt install --yes fsharp nunit-console
    - name: check mono version
      run: mono --version
    - name: run
      run: make run

  linux22-github--dotnet-and-newmono:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: install missing dependencies
      run: sudo apt install --yes fsharp nunit-console
    - name: install last version of mono (Microsoft APT repositories)
      run: sudo ./scripts/install_mono_from_microsoft_deb_packages.sh
    - name: check mono version
      run: mono --version
    - name: run
      run: make run

  linux22-vanilla--stockmono-only:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
    - uses: actions/checkout@v1
    # can't use the option below because of error "Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH."
    #  with:
    #    submodules: 'true'

    - name: install sudo
      run: apt update && apt install --yes sudo
    - name: install all dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt install --yes git make curl fsharp nunit-console

    # workaround for https://github.com/actions/runner/issues/2033
    - name: ownership workaround
      run: git config --global --add safe.directory '*'

    - name: check mono version
      run: mono --version
    - name: run
      run: make run

  linux22-vanilla--stockdotnet6-only:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
    - uses: actions/checkout@v1
    # can't use the option below because of error "Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH."
    #  with:
    #    submodules: 'true'

    - name: install sudo
      run: apt update && apt install --yes sudo
    - name: install all dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt install --yes git make curl dotnet6

    # workaround for https://github.com/actions/runner/issues/2033
    - name: ownership workaround
      run: git config --global --add safe.directory '*'

    - name: run
      run: make run

  linux22-vanilla--stockdotnet6-and-newmono:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
    - uses: actions/checkout@v1
    # can't use the option below because of error "Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH."
    #  with:
    #    submodules: 'true'

    - name: install sudo
      run: apt update && apt install --yes sudo
    - name: install all dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt install --yes git make curl dotnet6
    - name: install last version of mono (Microsoft APT repositories)
      run: sudo ./scripts/install_mono_from_microsoft_deb_packages.sh

    # workaround for https://github.com/actions/runner/issues/2033
    - name: ownership workaround
      run: git config --global --add safe.directory '*'

    - name: run
      run: make run

  linux22-vanilla--stockdotnet6-and-stockmono:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
    - uses: actions/checkout@v1
    # can't use the option below because of error "Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH."
    #  with:
    #    submodules: 'true'

    - name: install sudo
      run: apt update && apt install --yes sudo
    - name: install all dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt install --yes git make curl dotnet6 mono-xbuild

    # workaround for https://github.com/actions/runner/issues/2033
    - name: ownership workaround
      run: git config --global --add safe.directory '*'

    - name: run
      run: make run

  linux22-vanilla--newmono-only:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
    - uses: actions/checkout@v1
    # can't use the option below because of error "Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH."
    #  with:
    #    submodules: 'true'

    - name: install sudo
      run: apt update && apt install --yes sudo
    - name: install all dependencies
      run: sudo DEBIAN_FRONTEND=noninteractive apt install --yes git make curl fsharp nunit-console
    - name: install last version of mono (Microsoft APT repositories)
      run: sudo ./scripts/install_mono_from_microsoft_deb_packages.sh

    # workaround for https://github.com/actions/runner/issues/2033
    - name: ownership workaround
      run: git config --global --add safe.directory '*'

    - name: check mono version
      run: mono --version
    - name: run
      run: make run

  linux20-github--dotnet-and-mono:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false
    - name: install missing dependencies
      run: sudo apt install --yes fsharp nunit-console
    - name: check mono version
      run: mono --version
    - name: run
      run: make run

  linux20-github--dotnet-and-newmono:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install missing dependencies
      run: sudo apt install --yes fsharp nunit-console
    - name: install last version of mono (Microsoft APT repositories)
      run: sudo ./scripts/install_mono_from_microsoft_deb_packages.sh
    - name: check mono version
      run: mono --version
    - name: run
      run: make run

  linux20-vanilla--stockmono-only:
    runs-on: ubuntu-20.04
    container:
      image: "ubuntu:20.04"
    steps:
    - uses: actions/checkout@v1
    # can't use the option below because of error "Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH."
    #  with:
    #    submodules: 'true'

    - name: install sudo
      run: apt update && apt install --yes sudo
    - name: install all dependencies
      run: sudo apt install --yes git make curl fsharp nunit-console

    # workaround for https://github.com/actions/runner/issues/2033
    - name: ownership workaround
      run: git config --global --add safe.directory '*'

    - name: check mono version
      run: mono --version
    - name: run
      run: make run

  linux20-vanilla--newmono-only:
    runs-on: ubuntu-20.04
    container:
      image: "ubuntu:20.04"
    steps:
    - uses: actions/checkout@v1
    # can't use the option below because of error "Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH."
    #  with:
    #    submodules: 'true'

    - name: install sudo
      run: apt update && apt install --yes sudo
    - name: install all dependencies
      run: sudo apt install --yes git make curl fsharp nunit-console
    - name: install last version of mono (Microsoft APT repositories)
      run: sudo ./scripts/install_mono_from_microsoft_deb_packages.sh

    # workaround for https://github.com/actions/runner/issues/2033
    - name: ownership workaround
      run: git config --global --add safe.directory '*'

    - name: check mono version
      run: mono --version
    - name: run
      run: make run
